services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fusionauth
      POSTGRES_PASSWORD: hkaLBM3RVnyYeYeqE3Gi
      POSTGRES_DB: fusionauth
    ports:
      - "5434:5432"  # Changed from 5432 to avoid conflict with rasa-postgres on 5433
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fusionauth"]
      interval: 5s
      timeout: 5s
      retries: 5

  fusionauth:
    image: fusionauth/fusionauth-app:1.50.1
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: fusionauth
      DATABASE_ROOT_PASSWORD: hkaLBM3RVnyYeYeqE3Gi
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: hkaLBM3RVnyYeYeqE3Gi
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
    ports:
      - "9011:9011"  # Using standard FusionAuth port
    volumes:
      - ./kickstart:/usr/local/fusionauth/kickstart
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9011/api/status"]
      interval: 10s
      timeout: 5s
      retries: 10

  aaa-service:
    build: ./aaa-service
    depends_on:
      fusionauth:
        condition: service_healthy
    environment:
      FUSIONAUTH_BASE_URL: http://fusionauth:9011
      FUSIONAUTH_API_KEY: changeme-api-key
      FUSIONAUTH_TENANT_ID: ""
      FUSIONAUTH_APPLICATION_ID: 6bd5d02c-99b4-4338-9336-3f7572fd3c40
      JWT_EXPECTED_ISS: acme.com
      JWT_EXPECTED_AUD: 6bd5d02c-99b4-4338-9336-3f7572fd3c40
      JWKS_CACHE_TTL_SECONDS: 300
    ports:
      - "8080:8080"  # AAA service port (no conflict with existing services)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: