name: Publish SnapAuth Container

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./snapauth
          file: snapauth/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare release metadata
        id: release_prep
        run: |
          echo "tag=snapauth-$(git rev-parse --short $GITHUB_SHA)" >> "$GITHUB_OUTPUT"
          echo "digest=${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_prep.outputs.tag }}
          name: SnapAuth ${{ steps.release_prep.outputs.tag }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            snapauth/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Annotate release with image digest
        run: |
          gh release edit "${{ steps.release_prep.outputs.tag }}" \
            --notes "Image digest: ${{ steps.release_prep.outputs.digest }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
